services:
  - type: web
    name: schoolplus
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
    autoDeploy: true
